### ISSUE TITLE
Comment geo-feature

### ISSUE THREAD

**Issue by filipzava** [GeoSmartCity-CIP/gsc-client#11]
Responsible partner: TRACASA

**Comment by jruizaranguren** [comment]
This requirement still needs to be specified. I hope it will be more clear when the core of the API is done.

**Comment by filipzava** [comment]
So do you think this is not a part of the core API ? And who will specify it ?

**Comment by jruizaranguren** [comment]
Who did make the features breakdown?

**Comment by filipzava** [comment]
Yes, of course. And do you know who made it? Thx

**Comment by pgcipriano** [comment]
Comment geo-feature can be simply implemented as an edit of a free text attribute (e.g. WFS-T).
About "who made the breakdown" ... once again I remind you that GISIG and Sinergis did it, in late July 2015 ... since no other WP5 partners already did it before :)
We then discussed the breakdown with you both (Tracasa and Intergraph CZ) as well as other partners, several times from early August to September 11th to Girona project meeting in October.
